import { User } from '../../types/interfaces';
import { USER_STATUS, USER_ROLES } from '../../types/enums';

export const rows: User[] = [
  {
    id: '1',
    username: 'Mark Antonii',
    email: 'markantonii@gmail.com',
    status: USER_STATUS.ACTIVE,
    role: USER_ROLES.ADMIN,
  },
  {
    id: '2',
    username: 'Mark Antonii',
    email: 'markantonii@gmail.com',
    status: USER_STATUS.ACTIVE,
    role: USER_ROLES.ADMIN,
  },
  {
    id: '3',
    username: 'Mark Antonii',
    email: 'markantonii@gmail.com',
    status: USER_STATUS.ACTIVE,
    role: USER_ROLES.ADMIN,
  },
  {
    id: '4',
    username: 'Mark Antonii',
    email: 'markantonii@gmail.com',
    status: USER_STATUS.ACTIVE,
    role: USER_ROLES.ADMIN,
  },
  {
    id: '5',
    username: 'Mark Antonii',
    email: 'markantonii@gmail.com',
    status: USER_STATUS.ACTIVE,
    role: USER_ROLES.ADMIN,
  },
  {
    id: '6',
    username: 'Mark Antonii',
    email: 'markantonii@gmail.com',
    status: USER_STATUS.ACTIVE,
    role: USER_ROLES.ADMIN,
  },
  {
    id: '7',
    username: 'Mark Antonii',
    email: 'markantonii@gmail.com',
    status: USER_STATUS.ACTIVE,
    role: USER_ROLES.ADMIN,
  },
  {
    id: '8',
    username: 'Mark Antonii',
    email: 'markantonii@gmail.com',
    status: USER_STATUS.ACTIVE,
    role: USER_ROLES.ADMIN,
  },
  {
    id: '9',
    username: 'Mark Antonii',
    email: 'markantonii@gmail.com',
    status: USER_STATUS.ACTIVE,
    role: USER_ROLES.ADMIN,
  },
  {
    id: '10',
    username: 'Mark Antonii',
    email: 'markantonii@gmail.com',
    status: USER_STATUS.ACTIVE,
    role: USER_ROLES.ADMIN,
  },
  {
    id: '11',
    username: 'Mark Antonii',
    email: 'markantonii@gmail.com',
    status: USER_STATUS.ACTIVE,
    role: USER_ROLES.ADMIN,
  },
  {
    id: '12',
    username: 'Mark Antonii',
    email: 'markantonii@gmail.com',
    status: USER_STATUS.ACTIVE,
    role: USER_ROLES.ADMIN,
  },
  {
    id: '13',
    username: 'Mark Antonii',
    email: 'markantonii@gmail.com',
    status: USER_STATUS.ACTIVE,
    role: USER_ROLES.ADMIN,
  },
  {
    id: '14',
    username: 'Mark Antonii',
    email: 'markantonii@gmail.com',
    status: USER_STATUS.ACTIVE,
    role: USER_ROLES.ADMIN,
  },
  {
    id: '15',
    username: 'Mark Antonii',
    email: 'markantonii@gmail.com',
    status: USER_STATUS.ACTIVE,
    role: USER_ROLES.ADMIN,
  },

  {
    id: '16',
    username: 'Mark Antonii',
    email: 'markantonii@gmail.com',
    status: USER_STATUS.ACTIVE,
    role: USER_ROLES.ADMIN,
  },
  {
    id: '17',
    username: 'Mark Antonii',
    email: 'markantonii@gmail.com',
    status: USER_STATUS.ACTIVE,
    role: USER_ROLES.ADMIN,
  },
  {
    id: '18',
    username: 'Mark Antonii',
    email: 'markantonii@gmail.com',
    status: USER_STATUS.ACTIVE,
    role: USER_ROLES.ADMIN,
  },
  {
    id: '19',
    username: 'Mark Antonii',
    email: 'markantonii@gmail.com',
    status: USER_STATUS.ACTIVE,
    role: USER_ROLES.ADMIN,
  },

  {
    id: '20',
    username: 'Mark Antonii',
    email: 'markantonii@gmail.com',
    status: USER_STATUS.ACTIVE,
    role: USER_ROLES.ADMIN,
  },
  {
    id: '21',
    username: 'Mark Antonii',
    email: 'markantonii@gmail.com',
    status: USER_STATUS.ACTIVE,
    role: USER_ROLES.ADMIN,
  },
  {
    id: '22',
    username: 'Mark Antonii',
    email: 'markantonii@gmail.com',
    status: USER_STATUS.ACTIVE,
    role: USER_ROLES.ADMIN,
  },
  {
    id: '23',
    username: 'Mark Antonii',
    email: 'markantonii@gmail.com',
    status: USER_STATUS.ACTIVE,
    role: USER_ROLES.ADMIN,
  },

  {
    id: '24',
    username: 'Mark Antonii',
    email: 'markantonii@gmail.com',
    status: USER_STATUS.ACTIVE,
    role: USER_ROLES.ADMIN,
  },
  {
    id: '25',
    username: 'Mark Antonii',
    email: 'markantonii@gmail.com',
    status: USER_STATUS.ACTIVE,
    role: USER_ROLES.ADMIN,
  },
  {
    id: '26',
    username: 'Mark Antonii',
    email: 'markantonii@gmail.com',
    status: USER_STATUS.ACTIVE,
    role: USER_ROLES.ADMIN,
  },
  {
    id: '27',
    username: 'Mark Antonii',
    email: 'markantonii@gmail.com',
    status: USER_STATUS.ACTIVE,
    role: USER_ROLES.ADMIN,
  },
  {
    id: '28',
    username: 'Mark Antonii',
    email: 'markantonii@gmail.com',
    status: USER_STATUS.ACTIVE,
    role: USER_ROLES.ADMIN,
  },
  {
    id: '29',
    username: 'Mark Antonii',
    email: 'markantonii@gmail.com',
    status: USER_STATUS.ACTIVE,
    role: USER_ROLES.ADMIN,
  },
  {
    id: '30',
    username: 'Mark Antonii',
    email: 'markantonii@gmail.com',
    status: USER_STATUS.ACTIVE,
    role: USER_ROLES.ADMIN,
  },
  {
    id: '31',
    username: 'Mark Antonii',
    email: 'markantonii@gmail.com',
    status: USER_STATUS.ACTIVE,
    role: USER_ROLES.ADMIN,
  },
  {
    id: '32',
    username: 'Mark Antonii',
    email: 'markantonii@gmail.com',
    status: USER_STATUS.ACTIVE,
    role: USER_ROLES.ADMIN,
  },
  {
    id: '33',
    username: 'Mark Antonii',
    email: 'markantonii@gmail.com',
    status: USER_STATUS.ACTIVE,
    role: USER_ROLES.ADMIN,
  },
  {
    id: '34',
    username: 'Mark Antonii',
    email: 'markantonii@gmail.com',
    status: USER_STATUS.ACTIVE,
    role: USER_ROLES.ADMIN,
  },
  {
    id: '35',
    username: 'Mark Antonii',
    email: 'markantonii@gmail.com',
    status: USER_STATUS.ACTIVE,
    role: USER_ROLES.ADMIN,
  },

  {
    id: '36',
    username: 'Mark Antonii',
    email: 'markantonii@gmail.com',
    status: USER_STATUS.ACTIVE,
    role: USER_ROLES.ADMIN,
  },
  {
    id: '37',
    username: 'Mark Antonii',
    email: 'markantonii@gmail.com',
    status: USER_STATUS.ACTIVE,
    role: USER_ROLES.ADMIN,
  },
  {
    id: '38',
    username: 'Mark Antonii',
    email: 'markantonii@gmail.com',
    status: USER_STATUS.ACTIVE,
    role: USER_ROLES.ADMIN,
  },
  {
    id: '39',
    username: 'Mark Antonii',
    email: 'markantonii@gmail.com',
    status: USER_STATUS.ACTIVE,
    role: USER_ROLES.ADMIN,
  },
  {
    id: '40',
    username: 'Mark Antonii',
    email: 'markantonii@gmail.com',
    status: USER_STATUS.ACTIVE,
    role: USER_ROLES.ADMIN,
  },
  {
    id: '41',
    username: 'Mark Antonii',
    email: 'markantonii@gmail.com',
    status: USER_STATUS.ACTIVE,
    role: USER_ROLES.ADMIN,
  },
  {
    id: '42',
    username: 'Mark Antonii',
    email: 'markantonii@gmail.com',
    status: USER_STATUS.ACTIVE,
    role: USER_ROLES.ADMIN,
  },

  {
    id: '43',
    username: 'Mark Antonii',
    email: 'markantonii@gmail.com',
    status: USER_STATUS.ACTIVE,
    role: USER_ROLES.ADMIN,
  },
  {
    id: '44',
    username: 'Mark Antonii',
    email: 'markantonii@gmail.com',
    status: USER_STATUS.ACTIVE,
    role: USER_ROLES.ADMIN,
  },
  {
    id: '45',
    username: 'Mark Antonii',
    email: 'markantonii@gmail.com',
    status: USER_STATUS.ACTIVE,
    role: USER_ROLES.ADMIN,
  },
  {
    id: '46',
    username: 'Mark Antonii',
    email: 'markantonii@gmail.com',
    status: USER_STATUS.ACTIVE,
    role: USER_ROLES.ADMIN,
  },
  {
    id: '47',
    username: 'Mark Antonii',
    email: 'markantonii@gmail.com',
    status: USER_STATUS.ACTIVE,
    role: USER_ROLES.ADMIN,
  },
  {
    id: '48',
    username: 'Mark Antonii',
    email: 'markantonii@gmail.com',
    status: USER_STATUS.ACTIVE,
    role: USER_ROLES.ADMIN,
  },
  {
    id: '49',
    username: 'Mark Antonii',
    email: 'markantonii@gmail.com',
    status: USER_STATUS.ACTIVE,
    role: USER_ROLES.ADMIN,
  },
  {
    id: '50',
    username: 'Mark Antonii',
    email: 'markantonii@gmail.com',
    status: USER_STATUS.ACTIVE,
    role: USER_ROLES.ADMIN,
  },
  {
    id: '51',
    username: 'Mark Antonii',
    email: 'markantonii@gmail.com',
    status: USER_STATUS.ACTIVE,
    role: USER_ROLES.ADMIN,
  },
];
